fix: run all tests if branch is develop, main (#274)

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -87,8 +87,7 @@ jobs:
       fail-fast: false
       matrix:
         # TODO: Remove dummy-pkg before release
-        package: ["shopping-assistant", "dummy-pkg"]
-    
+        package: ["shopping-assistant", "dummy-pkg"] 
     runs-on: ubuntu-latest
 
     steps:
@@ -106,15 +105,49 @@ jobs:
           mkdir dist
           uv build "packages/${{ matrix.package }}" --out-dir dist
 
-
           WHEEL_FILE=$(ls dist/*.whl)
           SDIST_FILE=$(ls dist/*.tar.gz)
 
-          echo "Found wheel file: $WHEEL_FILE"
-          echo "Found sdist file: $SDIST_FILE"
+          echo "Created wheel file: $WHEEL_FILE"
+          echo "Created sdist file: $SDIST_FILE"
 
           echo "WHEEL_FILE=$WHEEL_FILE" >> "$GITHUB_ENV"
           echo "SDIST_FILE=$SDIST_FILE" >> "$GITHUB_ENV"
+
+      - name: Upload package artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ matrix.package }}-${{ needs.validate_version.outputs.version }}
+          path: dist/
+
+
+  test_packages:
+    needs: [validate_version, build_packages]
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        package: ["shopping-assistant", "dummy-pkg"]
+    steps:
+      # TODO: Avoid checking out code if wheel can contain "tests" folder
+      # TODO: Perhaps test with build in one matrix is better. 
+      #       The tests step could just add test report as artifact which could be downloaded
+      #       separately to tag as ALL or PARTIAL
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v7
+
+      - name: Set up Python
+        run: uv python install "${{ env.PYTHON_VERSION }}"
+
+      
+      - name: Download package artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ matrix.package }}-${{ needs.validate_version.outputs.version }}
+          path: dist/
 
       - name: Setup test environment
         run: |
@@ -126,26 +159,44 @@ jobs:
           COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
         run: |
 
+          WHEEL_FILE=$(ls dist/*.whl)
+          SDIST_FILE=$(ls dist/*.tar.gz)
+
+          echo "Found wheel file: $WHEEL_FILE"
+          echo "Found sdist file: $SDIST_FILE"
+
           # force re-install built wheel file (to avoid running tests against local imports)
           uv pip install "$WHEEL_FILE" --force-reinstall --python "packages/${{ matrix.package }}/.venv"
           cd packages/${{ matrix.package }}
 
           source .venv/bin/activate
 
+          # pkg="${{ matrix.package }}"
+          # pkg_var="${pkg//-/_}" 
+          status_var="TEST_STATUS" 
+
           # check if commit message starts with [include-slow-tests]
-          if [[ "$COMMIT_MESSAGE" == "[include-slow-tests]"* ]]; then
+          # Always run all tests if the branch is in [develop, main, fix/develop-ci-tests-bug]
+          if [[ "$COMMIT_MESSAGE" == "[include-slow-tests]"* ]] || [[ "${{ github.ref_name }}" = "develop" ]] || [[ "${{ github.ref_name }}" = "main" ]]; then
             echo "Running all tests including slow ones"
             pytest
+            echo "${status_var}=ALL" >> "$GITHUB_ENV"
           else
             echo "Running tests excluding slow ones"
             pytest -m "not slow"
+            echo "${status_var}=PARTIAL" >> "$GITHUB_ENV"
           fi
 
-      - name: Upload package artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.package }}-${{ needs.validate_version.outputs.version }}
-          path: dist/
+      - name: Test status (ALL or PARTIAL)
+        run: |
+          
+          if [ "${{ env.TEST_STATUS }}" = "ALL" ]; then
+            echo "All tests passed"
+            exit 0
+          else
+            echo "Partial tests passed"
+            exit 1
+          fi
 
 
   upload_packages:
@@ -162,20 +213,14 @@ jobs:
           name: all-packages-${{ needs.validate_version.outputs.version }}
           path: dist/
 
-  all_checks_pass_gate:
-    needs: [upload_packages]
+  
+  final_status:
     runs-on: ubuntu-latest
-    env:
-      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
+    needs: [test_packages]
+    if: always()
     steps:
-      - name: Check if all tests were run (and passed)
+      - name: Check for any failures
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped')
         run: |
-          # TODO: Make this generic enough to not rely on commit message at two places to
-          #       identify if all or partial tests were run
-          if [[ "$COMMIT_MESSAGE" == "[include-slow-tests]"* ]]; then
-            echo "All tests were run (including slow ones)"
-            exit 0
-          else
-            echo "All tests were not run: slow tests were excluded. Failing the workflow."
-            exit 1
-          fi
+          echo "One or more jobs failed or were cancelled."
+          exit 1
